kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    name: svc-monitor
spec:
  type: NodePort
  selector:
    name: app
  ports:
  - protocol: TCP
    nodePort: 30030
    name: http-metrics-app
    port: 80
    targetPort: 80
