apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: grafana/tns-db:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        ports:
        - containerPort: 80
        env:
          - name: JAEGER_COLLECTOR_URL
            value: http://tempo.tempo:14268
          - name: JAEGER_TAGS
            value: app=db,job=default/db
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_AGENT_HOST
            value: tempo.tempo.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
