#This service monitor will be translated into a scrape_config
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-svc-monitor
  labels:
    release: monitoring #todo this is defined in the prometheus deployment
spec:
#  jobLabel: tns/db
#  targetLabels:
#    - tns/db
  targetLabels:
    - custom_job_label
  selector:
    matchLabels:
      name: svc-monitor
  namespaceSelector:
    any: true
#    matchNames:
#      - default
  endpoints:
    - port: http-metrics-db
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [ job ]
          targetLabel: job
          replacement: tns/db
          action: replace
