kind: Service
apiVersion: v1
metadata:
  name: loadgen
  labels:
    name: svc-monitor
spec:
  selector:
    name: loadgen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http-metrics-loadgen
