apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
#         sidecar.opentelemetry.io/inject: "true"
        # instrumentation.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/inject-java: "opentelemetry-operator-system/tempo-instrumentation"
      labels:
        app: spring-boot
        {{- include "app.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: fran
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-management
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 5
            failureThreshold: 30
          env:
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: http://otel-tempo-collector.opentelemetry-operator-system:4317
            - name: SERVER_PORT
              value: '8080'
            - name: MANAGEMENT_SERVER_PORT
              value: '8081'
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pod=$(KUBE_POD_NAME),namespace={{ .Release.Namespace }},job=spring-boot
