apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: tempo-instrumentation
spec:
  exporter:
    endpoint: http://otel-tempo-collector.opentelemetry-operator-system:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      # Required if endpoint is set to 4317.
      # Java autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-tempo-collector.opentelemetry-operator-system:4318
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_TIMEOUT
        value: "200"
      - name: OTEL_TRACES_SAMPLER
        value: parentbased_traceidratio
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "0.85"
      # - name: OTEL_EXPORTER_OTLP_ENDPOINT
      #   value: http://tempo.tempo:4317
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
  dotnet:
    env:
      # Required if endpoint is set to 4317.
      # Dotnet autoinstrumentation uses http/proto by default
      # See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/888e2cd216c77d12e56b54ee91dafbc4e7452a52/docs/config.md#otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
  go:
    env:
      # Required if endpoint is set to 4317.
      # Go autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
# apiVersion: opentelemetry.io/v1alpha1
# kind: Instrumentation
# metadata:
#   name: tempo-instrumentation
# spec:
#   env:
#     - name: OTEL_TRACES_EXPORTER
#       value: otlp
#     - name: OTEL_EXPORTER_OTLP_TIMEOUT
#       value: "200"
#     - name: OTEL_TRACES_SAMPLER
#       value: parentbased_traceidratio
#     - name: OTEL_TRACES_SAMPLER_ARG
#       value: "0.85"
#     - name: OTEL_EXPORTER_OTLP_ENDPOINT
#       value: http://tempo.tempo:4317
# #     - name: OTEL_RESOURCE_ATTRIBUTES
# #       value: pod=$(KUBE_POD_NAME),namespace={{ .Release.Namespace }}
#   exporter:
#     endpoint: http://otel-tempo-collector:4317
#   propagators:
#     - tracecontext
#     - baggage
#     - b3
#   sampler:
#     type: parentbased_traceidratio
#     argument: "0.25"
#   java:
#     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
#   nodejs:
#     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
#   python:
#     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
