apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-tempo
spec:
  config: |
    receivers:
     otlp:
       protocols:
         grpc:
         http:

    processors:
     batch:


    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: "http://tempo.tempo:4317"
        tls:
          insecure: true

    service:
     pipelines:
       traces:
         receivers: [otlp]
         processors: [batch]
         exporters: [otlp,logging]


  mode: deployment
