apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-tempo
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      debug:

      prometheusremotewrite:
        endpoint: prometheus:9090 # Prometheus remote write endpoint
        tls:
          insecure: true
        external_labels:
          source: otelcol
          cluster: kubernetes-cluster

      otlphttp/loki:
        endpoint: "http://loki-gateway.loki.svc.cluster.local/otlp"
        tls:
          insecure: true
      # loki:
      #   endpoint: http://loki-loki-distributed-gateway/loki/api/v1/push
      #   tls:
      #     insecure: true
      otlp/tempo:
        endpoint: "http://tempo.tempo:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo, debug]
        # metrics:
        #   receivers: [otlp]
        #   processors: [batch]
        #   exporters: [otlp, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers:
            - otlp
          processors:
            # - memory_limiter
            # - attributes/loki
            # - resource/loki
            - batch
          exporters:
            # - debug/normal
            - otlphttp/loki
            # - loki

  mode: deployment
