apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: tempo-instrumentation
spec:
  env:
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "200"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.85"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://tempo.tempo:4317
#     - name: OTEL_RESOURCE_ATTRIBUTES
#       value: pod=$(KUBE_POD_NAME),namespace={{ .Release.Namespace }}
  exporter:
    endpoint: http://otel-tempo-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
