{
 "title": "Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))by (uri,method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Sudden changes in throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "holt_winters(instance:http_server_requests_seconds_count:rate1m[1m], 0.5, 0.2) * 0.7",
     "legendFormat": "smoothed"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (instance)",
     "legendFormat": "true"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_count[1m])) by (instance)) - (holt_winters(instance:http_server_requests_seconds_count:rate1m[1m], 0.5, 0.2) * 0.7)",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{le=~\"0\\\\.[0-4]\\\\d+|\\\\+Inf\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Max Latency by Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max) by (uri,method,instance)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "99th Percentile Latency by Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}