{
 "title": "SLIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le, verb))"
    }
   ]
  },
  {
   "title": "Throughput (time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Availability (% - line graph or text)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..\"}[5m])) / sum(rate(flask_http_request_total[5m]))"
    }
   ]
  },
  {
   "title": "Error Budget - Remaining Error Budget",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(flask_http_request_total{job=\"ec2\", status=~\"2..\"}[7d])) by (verb)) /  sum(increase(flask_http_request_total{job=\"ec2\"}[7d])) by (verb)) / (1 - .80))\n"
    }
   ]
  }
 ]
}